# Generated by Django 5.1.6 on 2025-03-16 04:23

import apps.colaborador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, validators=[apps.colaborador.models.validar_nome])),
                ('matricula', models.CharField(max_length=50)),
                ('pa', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, validators=[apps.colaborador.models.validar_pa])),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=20)),
                ('tipo', models.CharField(choices=[('Motorista', 'Motorista'), ('Coletor', 'Coletor'), ('Operador', 'Operador')], max_length=20, validators=[apps.colaborador.models.validar_colaborador])),
            ],
        ),
    ]
