# Generated by Django 5.1.6 on 2025-03-16 04:23

import apps.veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, validators=[apps.veiculos.models.validar_placa])),
                ('tipo', models.CharField(choices=[('Baú', 'Baú'), ('Seletolux', 'Seletolux'), ('Basculante', 'Basculante')], max_length=50)),
                ('prefixo', models.CharField(choices=[('BS', 'BS'), ('BAÚ', 'BAÚ'), ('SL', 'SL')], max_length=50)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=50, validators=[apps.veiculos.models.validar_status])),
                ('motivo_inatividade', models.CharField(blank=True, choices=[('Em manutenção', 'Em manutenção'), ('Na garagem', 'Na garagem')], max_length=50, null=True)),
            ],
        ),
    ]
